// World Taekwondo Member National Associations (MNA) names, NOC codes, and ISO 2-letter codes for flags
export const COUNTRY_LIST = [
  { noc: 'AFG', iso: 'af', name: 'Afghanistan' },
  { noc: 'ALB', iso: 'al', name: 'Albania' },
  { noc: 'ALG', iso: 'dz', name: 'Algeria' },
  { noc: 'ASA', iso: 'as', name: 'American Samoa' },
  { noc: 'AND', iso: 'ad', name: 'Andorra' },
  { noc: 'ANG', iso: 'ao', name: 'Angola' },
  { noc: 'ANT', iso: 'ag', name: 'Antigua and Barbuda' },
  { noc: 'ARG', iso: 'ar', name: 'Argentina' },
  { noc: 'ARM', iso: 'am', name: 'Armenia' },
  { noc: 'ARU', iso: 'aw', name: 'Aruba' },
  { noc: 'AUS', iso: 'au', name: 'Australia' },
  { noc: 'AUT', iso: 'at', name: 'Austria' },
  { noc: 'AZE', iso: 'az', name: 'Azerbaijan' },
  { noc: 'BAH', iso: 'bs', name: 'Bahamas' },
  { noc: 'BRN', iso: 'bh', name: 'Bahrain' },
  { noc: 'BAN', iso: 'bd', name: 'Bangladesh' },
  { noc: 'BAR', iso: 'bb', name: 'Barbados' },
  { noc: 'BLR', iso: 'by', name: 'Belarus' },
  { noc: 'BEL', iso: 'be', name: 'Belgium' },
  { noc: 'BIZ', iso: 'bz', name: 'Belize' },
  { noc: 'BEN', iso: 'bj', name: 'Benin' },
  { noc: 'BER', iso: 'bm', name: 'Bermuda' },
  { noc: 'BHU', iso: 'bt', name: 'Bhutan' },
  { noc: 'BOL', iso: 'bo', name: 'Bolivia' },
  { noc: 'BIH', iso: 'ba', name: 'Bosnia and Herzegovina' },
  { noc: 'BOT', iso: 'bw', name: 'Botswana' },
  { noc: 'BRA', iso: 'br', name: 'Brazil' },
  { noc: 'BRU', iso: 'bn', name: 'Brunei Darussalam' },
  { noc: 'BUL', iso: 'bg', name: 'Bulgaria' },
  { noc: 'BUR', iso: 'bf', name: 'Burkina Faso' },
  { noc: 'BDI', iso: 'bi', name: 'Burundi' },
  { noc: 'CAM', iso: 'kh', name: 'Cambodia' },
  { noc: 'CMR', iso: 'cm', name: 'Cameroon' },
  { noc: 'CAN', iso: 'ca', name: 'Canada' },
  { noc: 'CPV', iso: 'cv', name: 'Cape Verde' },
  { noc: 'CAY', iso: 'ky', name: 'Cayman Islands' },
  { noc: 'CAF', iso: 'cf', name: 'Central African Republic' },
  { noc: 'CHA', iso: 'td', name: 'Chad' },
  { noc: 'CHI', iso: 'cl', name: 'Chile' },
  { noc: 'TPE', iso: 'tw', name: 'Chinese Taipei' },
  { noc: 'COL', iso: 'co', name: 'Colombia' },
  { noc: 'KM',  iso: 'km', name: 'Comoros' }, // NOC is COM, let's keep it clean
  { noc: 'COM', iso: 'km', name: 'Comoros' },
  { noc: 'CGO', iso: 'cg', name: 'Congo' },
  { noc: 'COK', iso: 'ck', name: 'Cook Islands' },
  { noc: 'CRC', iso: 'cr', name: 'Costa Rica' },
  { noc: 'CIV', iso: 'ci', name: 'Cote d\'Ivoire' },
  { noc: 'CRO', iso: 'hr', name: 'Croatia' },
  { noc: 'CUB', iso: 'cu', name: 'Cuba' },
  { noc: 'CAO', iso: 'cw', name: 'Curacao' },
  { noc: 'CYP', iso: 'cy', name: 'Cyprus' },
  { noc: 'CZE', iso: 'cz', name: 'Czech Republic' },
  { noc: 'COD', iso: 'cd', name: 'Democratic Republic of the Congo' },
  { noc: 'DEN', iso: 'dk', name: 'Denmark' },
  { noc: 'DJI', iso: 'dj', name: 'Djibouti' },
  { noc: 'DOM', iso: 'do', name: 'Dominican Republic' },
  { noc: 'DMA', iso: 'dm', name: 'Dominica' },
  { noc: 'ECU', iso: 'ec', name: 'Ecuador' },
  { noc: 'EGY', iso: 'eg', name: 'Egypt' },
  { noc: 'ESA', iso: 'sv', name: 'El Salvador' },
  { noc: 'GEQ', iso: 'gq', name: 'Equatorial Guinea' },
  { noc: 'EST', iso: 'ee', name: 'Eonia' }, // Estonia
  { noc: 'EE',  iso: 'ee', name: 'Estonia' },
  { noc: 'SWZ', iso: 'sz', name: 'Eswatini' },
  { noc: 'ETH', iso: 'et', name: 'Ethiopia' },
  { noc: 'FSM', iso: 'fm', name: 'Federated States of Micronesia' },
  { noc: 'FIJ', iso: 'fj', name: 'Fiji' },
  { noc: 'FIN', iso: 'fi', name: 'Finland' },
  { noc: 'FRA', iso: 'fr', name: 'France' },
  { noc: 'FGT', iso: 'gf', name: 'French Guiana' },
  { noc: 'FPO', iso: 'pf', name: 'French Polynesia' },
  { noc: 'GAB', iso: 'ga', name: 'Gabon' },
  { noc: 'GAM', iso: 'gm', name: 'Gambia' },
  { noc: 'GEO', iso: 'ge', name: 'Georgia' },
  { noc: 'GER', iso: 'de', name: 'Germany' },
  { noc: 'GHA', iso: 'gh', name: 'Ghana' },
  { noc: 'GBR', iso: 'gb', name: 'Great Britain' },
  { noc: 'GRE', iso: 'gr', name: 'Greece' },
  { noc: 'GRN', iso: 'gd', name: 'Grenada' },
  { noc: 'GDL', iso: 'gp', name: 'Guadeloupe' },
  { noc: 'GUM', iso: 'gu', name: 'Guam' },
  { noc: 'GUA', iso: 'gt', name: 'Guatemala' },
  { noc: 'GUI', iso: 'gn', name: 'Guinea' },
  { noc: 'GBS', iso: 'gw', name: 'Guinea-Bissau' },
  { noc: 'GUY', iso: 'gy', name: 'Guyana' },
  { noc: 'HAI', iso: 'ht', name: 'Haiti' },
  { noc: 'HON', iso: 'hn', name: 'Honduras' },
  { noc: 'HKG', iso: 'hk', name: 'Hong Kong' },
  { noc: 'HUN', iso: 'hu', name: 'Hungary' },
  { noc: 'ISL', iso: 'is', name: 'Iceland' },
  { noc: 'IND', iso: 'in', name: 'India' },
  { noc: 'INA', iso: 'id', name: 'Indonesia' },
  { noc: 'IRQ', iso: 'iq', name: 'Iraq' },
  { noc: 'IRL', iso: 'ie', name: 'Ireland' },
  { noc: 'IRI', iso: 'ir', name: 'Islamic Republic of Iran' },
  { noc: 'IMN', iso: 'im', name: 'Isle of Man' },
  { noc: 'ISR', iso: 'il', name: 'Israel' },
  { noc: 'ITA', iso: 'it', name: 'Italy' },
  { noc: 'JAM', iso: 'jm', name: 'Jamaica' },
  { noc: 'JPN', iso: 'jp', name: 'Japan' },
  { noc: 'JOR', iso: 'jo', name: 'Jordan' },
  { noc: 'KAZ', iso: 'kz', name: 'Kazakhstan' },
  { noc: 'KEN', iso: 'ke', name: 'Kenya' },
  { noc: 'KIR', iso: 'ki', name: 'Kiribati' },
  { noc: 'KOS', iso: 'xk', name: 'Kosovo' },
  { noc: 'KUW', iso: 'kw', name: 'Kuwait' },
  { noc: 'KGZ', iso: 'kg', name: 'Kyrgyzstan' },
  { noc: 'LAO', iso: 'la', name: 'Lao People\'s Democratic Republic' },
  { noc: 'LAT', iso: 'lv', name: 'Latvia' },
  { noc: 'LIB', iso: 'lb', name: 'Lebanon' },
  { noc: 'LES', iso: 'ls', name: 'Lesotho' },
  { noc: 'LBR', iso: 'lr', name: 'Liberia' },
  { noc: 'LBA', iso: 'ly', name: 'Libya' },
  { noc: 'LTU', iso: 'lt', name: 'Lithuania' },
  { noc: 'LUX', iso: 'lu', name: 'Luxembourg' },
  { noc: 'MAC', iso: 'mo', name: 'Macau' },
  { noc: 'MAD', iso: 'mg', name: 'Madagascar' },
  { noc: 'MAW', iso: 'mw', name: 'Malawi' },
  { noc: 'MAS', iso: 'my', name: 'Malaysia' },
  { noc: 'MLI', iso: 'ml', name: 'Mali' },
  { noc: 'MLT', iso: 'mt', name: 'Malta' },
  { noc: 'MHL', iso: 'mh', name: 'Marshall Islands' },
  { noc: 'MRN', iso: 'mq', name: 'Martinique' },
  { noc: 'MTN', iso: 'mr', name: 'Mauritania' },
  { noc: 'MRI', iso: 'mu', name: 'Mauritius' },
  { noc: 'MEX', iso: 'mx', name: 'Mexico' },
  { noc: 'MON', iso: 'mc', name: 'Monaco' },
  { noc: 'MGL', iso: 'mn', name: 'Mongolia' },
  { noc: 'MNE', iso: 'me', name: 'Montenegro' },
  { noc: 'MAR', iso: 'ma', name: 'Morocco' },
  { noc: 'MOZ', iso: 'mz', name: 'Mozambique' },
  { noc: 'MYA', iso: 'mm', name: 'Myanmar' },
  { noc: 'NRU', iso: 'nr', name: 'Nauru' },
  { noc: 'NEP', iso: 'np', name: 'Nepal' },
  { noc: 'NED', iso: 'nl', name: 'Netherlands' },
  { noc: 'NCD', iso: 'nc', name: 'New Caledonia' },
  { noc: 'NZL', iso: 'nz', name: 'New Zealand' },
  { noc: 'NCA', iso: 'ni', name: 'Nicaragua' },
  { noc: 'NIG', iso: 'ne', name: 'Niger' },
  { noc: 'NGR', iso: 'ng', name: 'Nigeria' },
  { noc: 'MKD', iso: 'mk', name: 'North Macedonia' },
  { noc: 'NOR', iso: 'no', name: 'Norway' },
  { noc: 'OMA', iso: 'om', name: 'Oman' },
  { noc: 'PAK', iso: 'pk', name: 'Pakistan' },
  { noc: 'PLW', iso: 'pw', name: 'Palau' },
  { noc: 'PLE', iso: 'ps', name: 'Palestine' },
  { noc: 'PAN', iso: 'pa', name: 'Panama' },
  { noc: 'PNG', iso: 'pg', name: 'Papua New Guinea' },
  { noc: 'PAR', iso: 'py', name: 'Paraguay' },
  { noc: 'CHN', iso: 'cn', name: 'People\'s Republic of China' },
  { noc: 'PER', iso: 'pe', name: 'Peru' },
  { noc: 'PHI', iso: 'ph', name: 'Philippines' },
  { noc: 'POL', iso: 'pl', name: 'Poland' },
  { noc: 'POR', iso: 'pt', name: 'Portugal' },
  { noc: 'PUR', iso: 'pr', name: 'Puerto Rico' },
  { noc: 'QAT', iso: 'qa', name: 'Qatar' },
  { noc: 'KOR', iso: 'kr', name: 'Republic of Korea' },
  { noc: 'MDA', iso: 'md', name: 'Republic of Moldova' },
  { noc: 'ROU', iso: 'ro', name: 'Romania' },
  { noc: 'RUS', iso: 'ru', name: 'Russian Federation' },
  { noc: 'RWA', iso: 'rw', name: 'Rwanda' },
  { noc: 'SKN', iso: 'kn', name: 'Saint Kitts and Nevis' },
  { noc: 'LCA', iso: 'lc', name: 'Saint Lucia' },
  { noc: 'VIN', iso: 'vc', name: 'Saint Vincent and the Grenadines' },
  { noc: 'SAM', iso: 'ws', name: 'Samoa' },
  { noc: 'SMR', iso: 'sm', name: 'San Marino' },
  { noc: 'STP', iso: 'st', name: 'Sao Tome and Principe' },
  { noc: 'KSA', iso: 'sa', name: 'Saudi Arabia' },
  { noc: 'SEN', iso: 'sn', name: 'Senegal' },
  { noc: 'SRB', iso: 'rs', name: 'Serbia' },
  { noc: 'SYC', iso: 'sc', name: 'Seychelles' },
  { noc: 'SLE', iso: 'sl', name: 'Sierra Leone' },
  { noc: 'SIN', iso: 'sg', name: 'Singapore' },
  { noc: 'SVK', iso: 'sk', name: 'Slovakia' },
  { noc: 'SLO', iso: 'si', name: 'Slovenia' },
  { noc: 'SOL', iso: 'sb', name: 'Solomon Islands' },
  { noc: 'SOM', iso: 'so', name: 'Somalia' },
  { noc: 'RSA', iso: 'za', name: 'South Africa' },
  { noc: 'SSD', iso: 'ss', name: 'South Sudan' },
  { noc: 'ESP', iso: 'es', name: 'Spain' },
  { noc: 'SRI', iso: 'lk', name: 'Sri Lanka' },
  { noc: 'SUD', iso: 'sd', name: 'Sudan' },
  { noc: 'SUR', iso: 'sr', name: 'Suriname' },
  { noc: 'SWE', iso: 'se', name: 'Sweden' },
  { noc: 'SUI', iso: 'ch', name: 'Switzerland' },
  { noc: 'SYR', iso: 'sy', name: 'Syrian Arab Republic' },
  { noc: 'TJK', iso: 'tj', name: 'Tajikistan' },
  { noc: 'THA', iso: 'th', name: 'Thailand' },
  { noc: 'TLS', iso: 'tl', name: 'Timor-Leste' },
  { noc: 'TOG', iso: 'tg', name: 'Togo' },
  { noc: 'TGA', iso: 'to', name: 'Tonga' },
  { noc: 'TTO', iso: 'tt', name: 'Trinidad and Tobago' },
  { noc: 'TUN', iso: 'tn', name: 'Tunisia' },
  { noc: 'TUR', iso: 'tr', name: 'Turkey' },
  { noc: 'TKM', iso: 'tm', name: 'Turkmenistan' },
  { noc: 'TUV', iso: 'tv', name: 'Tuvalu' },
  { noc: 'UGA', iso: 'ug', name: 'Uganda' },
  { noc: 'UKR', iso: 'ua', name: 'Ukraine' },
  { noc: 'UAE', iso: 'ae', name: 'United Arab Emirates' },
  { noc: 'TAN', iso: 'tz', name: 'United Republic of Tanzania' },
  { noc: 'USA', iso: 'us', name: 'United States of America' },
  { noc: 'URU', iso: 'uy', name: 'Uruguay' },
  { noc: 'UZB', iso: 'uz', name: 'Uzbekistan' },
  { noc: 'VAN', iso: 'vu', name: 'Vanuatu' },
  { noc: 'VEN', iso: 've', name: 'Venezuela' },
  { noc: 'VIE', iso: 'vn', name: 'Vietnam' },
  { noc: 'IVB', iso: 'vg', name: 'Virgin Islands, British' },
  { noc: 'ISV', iso: 'vi', name: 'Virgin Islands, US' },
  { noc: 'YEM', iso: 'ye', name: 'Yemen' },
  { noc: 'ZAM', iso: 'zm', name: 'Zambia' },
  { noc: 'ZIM', iso: 'zw', name: 'Zimbabwe' }
];

// Helper to convert WT NOC code (3 letters) to FlagCDN ISO code (2 letters)
export const nocToIso = (nocCode) => {
  if (!nocCode) return 'in'; // default to India
  const upper = nocCode.trim().toUpperCase();
  if (upper === 'NONE') return null;
  const match = COUNTRY_LIST.find(c => c.noc === upper);
  return match ? match.iso : upper.toLowerCase();
};
